package com.lethien.common_lib.event;

import lombok.*;

import java.io.Serializable;
import java.time.ZonedDateTime;
import java.util.UUID;

/**
 * AccountCreatedEvent
 *
 * Published by: Auth Service — when a new account is successfully registered.
 * Consumed by:  User Service  — to create the corresponding User profile.
 *
 * Transport: Kafka topic "auth.account.created"
 *
 * Serialization: JSON via Jackson (not Java native serialization).
 * Serializable is implemented for compatibility only — do NOT rely on
 * Java object streams. Always use an ObjectMapper to serialize/deserialize.
 *
 * Idempotency: Consumer must check eventId to skip duplicate deliveries.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AccountCreatedEvent implements Serializable {

    private static final long serialVersionUID = 1L;

    // ============================================
    // EVENT METADATA
    // ============================================

    /**
     * Unique event ID — generated by Auth Service at publish time.
     * Used by consumers for idempotency checks (skip if already processed).
     */
    @Builder.Default
    private UUID eventId = UUID.randomUUID();

    /**
     * Event type identifier — useful when multiple event types share a topic
     * or when routing/filtering in the consumer.
     * Fixed value: "ACCOUNT_CREATED"
     */
    @Builder.Default
    private String eventType = "ACCOUNT_CREATED";

    /**
     * When this event was generated by the publisher.
     * ZonedDateTime ensures timezone info is preserved across services.
     */
    @Builder.Default
    private ZonedDateTime occurredAt = ZonedDateTime.now();

    // ============================================
    // PAYLOAD
    // ============================================

    /**
     * Account ID from auth_db.accounts.
     * User Service uses this as both User.id (PK) and User.accountId.
     */
    private UUID accountId;

    /**
     * Email registered in Auth Service.
     * Stored in user_db.users.email for eventual consistency.
     */
    private String email;

    /**
     * Full name — stored as a single field in user_db.users.full_name.
     * User Service splits into firstName/lastName via business methods
     * on the User entity — no splitting done here.
     */
    private String fullName;

    private String phoneNumber;

    /**
     * When the account was created in auth_db.
     * Stored for audit trail in User Service.
     */
    private ZonedDateTime accountCreateAt;

    // ============================================
    // BUSINESS METHODS
    // ============================================

    /**
     * Idempotency key for consumer-side deduplication.
     * Combines eventType + accountId for a globally unique key.
     */
    public String idempotencyKey() {
        return this.eventType + ":" + this.accountId;
    }

    /**
     * Validate that required payload fields are present.
     * Call this in the consumer before processing.
     */
    public boolean isValid() {
        return this.accountId != null
                && this.email != null && !this.email.isBlank()
                && this.fullName != null && !this.fullName.isBlank()
                && this.phoneNumber!= null && !this.phoneNumber.isBlank();
    }
}
